---
- name: Configure Nginx for chronical sync
  hosts: localhost
  become: yes
  gather_facts: false

  vars:
    my_domain: "chroniclesync.xyz"
    project_path: "/home/posix4e/chroniclesync"

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy our custom Nginx config
      template:
        src: templates/chroniclesync.conf.j2
        dest: /etc/nginx/sites-available/chroniclesync.conf
      notify:
        - Reload Nginx

    - name: Disable default site (optional)
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify:
        - Reload Nginx

    - name: Enable our site
      file:
        src: /etc/nginx/sites-available/chroniclesync.conf
        dest: /etc/nginx/sites-enabled/chroniclesync.conf
        state: link
      notify:
        - Reload Nginx

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded

