name = "chronicle-sync"
main = "dist-worker/worker.js"
compatibility_date = "2023-12-01"

[env.staging]
name = "chronicle-sync-staging"
vars = { ENVIRONMENT = "staging" }

[[env.staging.r2_buckets]]
binding = "SYNC_BUCKET"
bucket_name = "chronicle-sync-staging"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "chronicle-sync-staging"
database_id = "D1_DB_ID"

[[env.staging.kv_namespaces]]
binding = "SYNC_KV"
id = "KV_NAMESPACE_ID"

[env.production]
name = "chronicle-sync"
vars = { ENVIRONMENT = "production" }

[[env.production.r2_buckets]]
binding = "SYNC_BUCKET"
bucket_name = "chronicle-sync"

[[env.production.d1_databases]]
binding = "DB"
database_name = "chronicle-sync"
database_id = "D1_DB_ID"

[[env.production.kv_namespaces]]
binding = "SYNC_KV"
id = "KV_NAMESPACE_ID"