name = "chronicle-sync-worker"
main = "src/worker.py"
compatibility_date = "2024-01-09"
compatibility_flags = ["python_workers"]

[vars]
ALLOWED_ORIGINS = "*"

[[kv_namespaces]]
binding = "SYNC_KV"
id = "sync-kv-id"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "chronicle-sync-storage"

[env.staging]
name = "chronicle-sync-worker-staging"
vars = { ALLOWED_ORIGINS = "https://staging.chroniclesync.xyz" }

[env.production]
name = "chronicle-sync-worker-prod"
vars = { ALLOWED_ORIGINS = "https://chroniclesync.xyz" }