title: Chronicle Sync
description: Cross-platform browser history synchronization with end-to-end encryption
theme: jekyll-theme-minimal

# Show screenshots at full size
kramdown:
  parse_block_html: true

# Custom styles
custom_css:
  - /assets/css/screenshots.css
  - /assets/css/gallery.css