name: CI

on:
  pull_request:
    branches: [ main, staging ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Verify
        run: |
          npm run lint
          npm test
          npm run test:e2e
          
          # Build packages and extensions
          npm run build:packages
          npm run build:chrome
          npm run build:firefox
        env:
          # Use placeholder values for testing
          SYNC_URL: https://test.chronicle-sync.dev
          VERSION: 0.0.0-test