name: CI/CD

on:
  push:
    branches: [main, staging]
    tags: ['v*']
  pull_request:
    branches: [main, staging]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run unit tests
        run: npm test -- --coverage
        env:
          CI: true

      - name: Upload test coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 14

      - name: Build extension
        if: success()
        run: npm run build
        env:
          NODE_ENV: production

      - name: Build worker
        if: success()
        run: npx webpack --config webpack.worker.js --mode production

      - name: Install Chrome
        if: success()
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Run E2E tests and generate screenshots
        if: success()
        run: |
          mkdir -p docs/screenshots/setup-flow
          xvfb-run --auto-servernum npm run test:e2e
          cp -r tests/screenshots/* docs/screenshots/ || true
        env:
          CI: true
          DISPLAY: :99
          CHROME_PATH: /usr/bin/google-chrome
          SCREENSHOTS_FOR_DOCS: true

      - name: Upload test artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-failure-artifacts
          path: |
            tests/screenshots/**/*.png
            tests/logs/
          retention-days: 7
          if-no-files-found: ignore

      - name: Update documentation
        if: success() && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
        run: |
          echo "# Latest Test Results" > docs/test-results.md
          echo "" >> docs/test-results.md
          echo "Last updated: $(date)" >> docs/test-results.md
          echo "" >> docs/test-results.md
          echo "## Test Screenshots" >> docs/test-results.md
          echo "" >> docs/test-results.md
          
          for dir in docs/screenshots/*; do
            if [ -d "$dir" ]; then
              test_name=$(basename "$dir")
              echo "### $test_name" >> docs/test-results.md
              echo "" >> docs/test-results.md
              
              for img in "$dir"/*.png; do
                if [ -f "$img" ]; then
                  name=$(basename "$img")
                  rel_path="screenshots/$test_name/$name"
                  echo "#### ${name%.png}" >> docs/test-results.md
                  echo "![${name%.png}]($rel_path)" >> docs/test-results.md
                  echo "" >> docs/test-results.md
                fi
              done
            fi
          done

      - name: Commit documentation changes
        if: success() && github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "openhands@all-hands.dev"
          git config --local user.name "openhands"
          git add docs
          git commit -m "Update documentation with latest screenshots" || exit 0
          git push

      - name: Package Extension
        if: success() && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
        run: |
          cd dist
          zip -r ../chronicle-sync.zip *

      - name: Configure GitHub Pages
        if: success() && github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        if: success() && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      - name: Deploy to GitHub Pages
        if: success() && github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4

      - name: Install Wrangler
        if: success() && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
        run: npm install -g wrangler@latest

      - name: Generate Wrangler Config
        if: success() && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
        run: ./scripts/generate-wrangler-config.sh
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          PROD_DB_ID: ${{ secrets.PROD_DB_ID }}
          PROD_KV_ID: ${{ secrets.PROD_KV_ID }}
          STAGING_DB_ID: ${{ secrets.STAGING_DB_ID }}
          STAGING_KV_ID: ${{ secrets.STAGING_KV_ID }}

      - name: Deploy to Cloudflare Staging
        if: success() && github.ref == 'refs/heads/main'
        run: wrangler deploy --env staging
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Create Beta Release
        if: success() && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: chronicle-sync.zip
          name: "Beta (Staging)"
          tag_name: beta
          prerelease: true
          body: |
            Beta version of Chronicle Sync extension connected to staging environment.
            This version is automatically updated when changes are merged to main.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Cloudflare Production
        if: success() && startsWith(github.ref, 'refs/tags/v')
        run: wrangler deploy --env production
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Create Production Release
        if: success() && startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: chronicle-sync.zip
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}