name: Deploy to Cloudflare Pages

on:
  workflow_run:
    workflows: ["CI/CD"]
    types:
      - completed
    branches: [main, staging]

permissions:
  contents: read
  deployments: write

jobs:
  build-and-deploy-staging:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9.15.2

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build dashboard
        run: |
          echo "Building dashboard..."
          pnpm webpack --config webpack.dashboard.js --mode production
          
          # Verify dashboard build succeeded
          if [ ! -d "dist/dashboard" ]; then
            echo "Error: Dashboard build failed"
            exit 1
          fi

      - name: Install Wrangler
        run: npm install -g wrangler@latest

      - name: Deploy Pages (Staging)
        run: |
          echo "Deploying dashboard to staging..."
          wrangler pages deploy dist/dashboard \
            --project-name chronicle-sync \
            --branch staging \
            --commit-dirty=true \
            --custom-domain dashboard-staging.chroniclesync.xyz
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Configure Staging Custom Domain
        run: |
          echo "Configuring custom domain for staging..."
          curl -X POST "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/pages/projects/chronicle-sync/domains" \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"name":"dashboard-staging.chroniclesync.xyz"}'
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  build-and-deploy-production:
    if: github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_branch, 'refs/tags/v')
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9.15.2

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build dashboard
        run: |
          echo "Building dashboard..."
          pnpm webpack --config webpack.dashboard.js --mode production
          
          # Verify dashboard build succeeded
          if [ ! -d "dist/dashboard" ]; then
            echo "Error: Dashboard build failed"
            exit 1
          fi

      - name: Install Wrangler
        run: npm install -g wrangler@latest

      - name: Deploy Pages (Production)
        run: |
          echo "Deploying dashboard to production..."
          wrangler pages deploy dist/dashboard \
            --project-name chronicle-sync \
            --branch main \
            --commit-dirty=true \
            --custom-domain dashboard.chroniclesync.xyz
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}