name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main, staging]

permissions:
  contents: read
  deployments: write

jobs:
  build-and-deploy-staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9.15.2

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build dashboard
        run: |
          echo "Building dashboard..."
          pnpm webpack --config webpack.dashboard.js --mode production
          
          # Verify dashboard build succeeded
          if [ ! -d "dist/dashboard" ]; then
            echo "Error: Dashboard build failed"
            exit 1
          fi

      - name: Install Wrangler
        run: npm install -g wrangler@latest

      # Pages project configuration is now handled through Cloudflare dashboard

      - name: Deploy Pages (Staging)
        run: |
          echo "Deploying dashboard to staging..."
          wrangler pages deploy dist/dashboard \
            --project-name chronicle-sync \
            --branch preview \
            --commit-dirty=true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      # Custom domains are now managed through Cloudflare dashboard

  build-and-deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9.15.2

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build dashboard
        run: |
          echo "Building dashboard..."
          pnpm webpack --config webpack.dashboard.js --mode production
          
          # Verify dashboard build succeeded
          if [ ! -d "dist/dashboard" ]; then
            echo "Error: Dashboard build failed"
            exit 1
          fi

      - name: Install Wrangler
        run: npm install -g wrangler@latest

      - name: Deploy Pages (Production)
        run: |
          echo "Deploying dashboard to production..."
          wrangler pages deploy dist/dashboard \
            --project-name chronicle-sync \
            --branch production \
            --commit-dirty=true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      # Custom domains are now managed through Cloudflare dashboard