name: Test

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: npm run lint
    
    - name: Run unit tests
      run: npm test
      env:
        CI: true
      
    - name: Upload test coverage
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage/
        retention-days: 14

  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
      env:
        NODE_ENV: production

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
    
    - name: Run end-to-end tests
      run: xvfb-run --auto-servernum npm run test:e2e
      env:
        CI: true
        DISPLAY: :99
        CHROME_PATH: /usr/bin/google-chrome
    
    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-artifacts
        path: |
          tests/screenshots/**/*.png
          tests/logs/
        retention-days: 7
        if-no-files-found: ignore

    - name: Copy screenshots to docs
      if: success()
      run: |
        mkdir -p docs/test-results/screenshots
        cp -r tests/screenshots/* docs/test-results/screenshots/ || true
        
    - name: Generate screenshots index
      if: success()
      run: |
        echo "# Test Screenshots" > docs/test-results/index.md
        echo "" >> docs/test-results/index.md
        echo "Last updated: $(date)" >> docs/test-results/index.md
        echo "" >> docs/test-results/index.md
        
        for dir in docs/test-results/screenshots/*; do
          if [ -d "$dir" ]; then
            test_name=$(basename "$dir")
            echo "## $test_name" >> docs/test-results/index.md
            echo "" >> docs/test-results/index.md
            
            for img in "$dir"/*.png; do
              if [ -f "$img" ]; then
                name=$(basename "$img")
                rel_path="screenshots/$test_name/$name"
                echo "### ${name%.png}" >> docs/test-results/index.md
                echo "![${name%.png}]($rel_path)" >> docs/test-results/index.md
                echo "" >> docs/test-results/index.md
              fi
            done
          fi
        done

    - name: Deploy to GitHub Pages
      if: success() && github.ref == 'refs/heads/main'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs
        clean: false