name: Test and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: always()  # Run on both success and failure
        with:
          name: test-screenshots
          path: screenshots/
          retention-days: 14

  deploy:
    needs: test  # Only run if tests pass
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'  # Only on main branch pushes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Download test screenshots
        uses: actions/download-artifact@v3
        with:
          name: test-screenshots
          path: screenshots/
          
      - name: Build and deploy webpage
        run: |
          npm run build
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}