name: Update Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
    
    - name: Build project
      run: npm run build
      env:
        NODE_ENV: production

    - name: Run E2E tests for screenshots
      run: xvfb-run --auto-servernum npm run test:e2e
      env:
        DISPLAY: :99
        CHROME_PATH: /usr/bin/google-chrome
        SCREENSHOTS_FOR_DOCS: true
    
    - name: Update documentation
      run: |
        # Create directory structure
        mkdir -p docs/screenshots/setup-flow
        
        # Copy screenshots
        cp -r tests/screenshots/* docs/screenshots/ || true
        
        # Update screenshot gallery
        echo "# Latest Test Results" > docs/test-results.md
        echo "" >> docs/test-results.md
        echo "Last updated: $(date)" >> docs/test-results.md
        echo "" >> docs/test-results.md
        echo "## Test Screenshots" >> docs/test-results.md
        echo "" >> docs/test-results.md
        
        for dir in docs/screenshots/*; do
          if [ -d "$dir" ]; then
            test_name=$(basename "$dir")
            echo "### $test_name" >> docs/test-results.md
            echo "" >> docs/test-results.md
            
            for img in "$dir"/*.png; do
              if [ -f "$img" ]; then
                name=$(basename "$img")
                rel_path="screenshots/$test_name/$name"
                echo "#### ${name%.png}" >> docs/test-results.md
                echo "![${name%.png}]($rel_path)" >> docs/test-results.md
                echo "" >> docs/test-results.md
              fi
            done
          fi
        done
    
    - name: Commit and push changes
      run: |
        git config --local user.email "openhands@all-hands.dev"
        git config --local user.name "openhands"
        git add docs
        git commit -m "Update documentation with latest screenshots" || exit 0
        git push